# Generated by Django 6.0.6 on 2026-07-06 12:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='モジュールコード')),
                ('name', models.CharField(max_length=100, verbose_name='モジュール名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'db_table': 'system_module',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=100, verbose_name='会社名')),
                ('subdomain', models.CharField(max_length=50, unique=True, verbose_name='サブドメイン')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効ステータス')),
                ('modules', models.ManyToManyField(blank=True, related_name='tenants', to='tenants.systemmodule', verbose_name='契約モジュール')),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_code', models.CharField(max_length=20, verbose_name='取引先コード')),
                ('customer_name', models.CharField(max_length=100, verbose_name='取引先名')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'customer',
                'unique_together': {('tenant', 'customer_code')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('project_code', models.CharField(max_length=20, verbose_name='案件コード')),
                ('project_name', models.CharField(max_length=100, verbose_name='案件名')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenants.customer', verbose_name='取引先')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenants.tenant')),
            ],
            options={
                'db_table': 'project',
                'unique_together': {('tenant', 'project_code')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department_code', models.CharField(max_length=20, verbose_name='部門コード')),
                ('department_name', models.CharField(max_length=100, verbose_name='部門名')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'department',
                'unique_together': {('tenant', 'department_code')},
            },
        ),
    ]
