# Generated by Django 6.0.6 on 2026-07-07 10:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150, verbose_name='精算タイトル')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('pending', '申請中'), ('approved', '精算完了'), ('rejected', '差し戻し')], default='draft', max_length=20, verbose_name='ステータス')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='合計金額')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='申請日時')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_approvals', to=settings.AUTH_USER_MODEL, verbose_name='現在の承認者')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='tenants.project', verbose_name='関連案件')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'db_table': 'expense_report',
            },
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('transport', '交通費'), ('meal', '会議費・交際費'), ('supplies', '消耗品費'), ('others', 'その他')], max_length=30, verbose_name='費目')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='金額')),
                ('expense_date', models.DateField(verbose_name='利用日')),
                ('description', models.TextField(blank=True, verbose_name='備考・用途')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expensereport', verbose_name='精算書')),
            ],
            options={
                'db_table': 'expense_item',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submit', '申請'), ('approve', '承認'), ('reject', '差し戻し'), ('cancel', '取下げ')], max_length=20, verbose_name='アクション')),
                ('comment', models.TextField(blank=True, verbose_name='コメント・理由')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_logs', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='tenants.tenant')),
                ('expense_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='expenses.expensereport', verbose_name='精算書')),
            ],
            options={
                'db_table': 'approval_log',
                'ordering': ['created_at'],
            },
        ),
    ]
